/**
 * The cover for one report, and the placeholder for an item with no picture.
 *
 * Drawn here, from the report's own number. Nothing is generated by a model
 * and nothing is fetched from an image service: the pictures in a report
 * belong to the publishers who took them, and the only image we make is this
 * one, which is a piece of our own branding rather than a depiction of
 * anything.
 *
 * It is a real design, not an error state, and that distinction carries weight
 * now. An item whose publisher offers no picture, or whose picture is a wire
 * photograph we will not point at, shows this instead - so it has to look like
 * a decision somebody made.
 *
 * Our blob store is private - it refuses `access: 'public'` outright - so the
 * stored URL is never the blob's own. It is an absolute link to
 * /api/report-cover, which streams the file to anybody who has the link. That
 * is deliberate and it is the only way round: the Monday email shows the cover,
 * and an email client fetches images with no cookies and no session.
 */
import { put } from '@vercel/blob';

/* ---------------- the drawing ---------------- */

const esc = (s) => String(s || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

/**
 * A cover drawn from the report's own number and title.
 *
 * Deterministic: the same report always gets the same cover, because a cover
 * that changes when a page is re-rendered looks like a bug. The hue comes from
 * the number, so consecutive reports sit apart on the shelf.
 *
 * No lettering on it. It used to set "REPORT 06" and the headline across the
 * bottom, which looked right in isolation and wrong everywhere it is actually
 * used: on the shelf the card already carries a "Report 6" badge and prints
 * the title immediately underneath, and above an open report the number is in
 * the meta line and the headline is the next thing down. The cover was saying
 * both of them a second time, in smaller type. The title is still taken as an
 * argument because the artwork is seeded from it and the alt text is built
 * from it.
 */
export function drawCover({ number, title, topic }) {
  const n = Number(number) || 1;

  // Inside the brand's own band rather than around the whole wheel. Thirty
  // degrees of amber-to-orange is enough to tell two covers apart on a shelf
  // and not enough for one of them to come out lime green.
  const hue = 14 + ((n * 7) % 31);
  const a = `hsl(${hue} 95% 60%)`;
  const b = `hsl(${(hue + 14) % 360} 88% 50%)`;

  const dots = [];
  for (let i = 0; i < 44; i++) {
    const x = 60 + ((i * 137 + n * 29) % 1080);
    const y = 36 + ((i * 263 + n * 61) % 392);
    const r = 1.5 + ((i + n) % 4);
    dots.push(`<circle cx="${x}" cy="${y}" r="${r}" fill="${i % 6 === 0 ? a : '#ffffff'}" opacity="${i % 6 === 0 ? 0.85 : 0.1}"/>`);
  }

  return `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="480" viewBox="0 0 1200 480" role="img" aria-label="${esc(title)}">
  <defs>
    <radialGradient id="g1" cx="76%" cy="8%" r="70%">
      <stop offset="0%" stop-color="${a}" stop-opacity=".30"/><stop offset="100%" stop-color="${a}" stop-opacity="0"/>
    </radialGradient>
    <radialGradient id="g2" cx="12%" cy="96%" r="62%">
      <stop offset="0%" stop-color="${b}" stop-opacity=".20"/><stop offset="100%" stop-color="${b}" stop-opacity="0"/>
    </radialGradient>
  </defs>
  <rect width="1200" height="480" fill="#0a0a0b"/>
  <rect width="1200" height="480" fill="url(#g1)"/>
  <rect width="1200" height="480" fill="url(#g2)"/>
  ${dots.join('')}
  <rect x="0" y="474" width="1200" height="6" fill="${a}"/>
</svg>`;
}

/* ---------------- storage ---------------- */

/* Where the cover is stored, and the one shape api/report-cover will serve.
   Anything outside this prefix is refused there, so the endpoint cannot be
   talked into streaming a lesson video or somebody's download. */
export const COVER_PREFIX = 'reports/cover-';

const site = () => (process.env.SITE_URL || 'https://aifounderuniversity.com').replace(/\/+$/, '');

/**
 * The link that goes in the database, the page and the email.
 *
 * Absolute, because the email needs it to be, and pointing at our own endpoint
 * rather than at the blob, because the blob is private and returns 403 to
 * anything without our token.
 */
export function coverHref(pathname) {
  return `${site()}/api/report-cover?key=${encodeURIComponent(pathname)}`;
}

/**
 * A cover for this report, in our own storage.
 *
 * Never throws. If it cannot be stored the report still goes out without one -
 * losing the week's report over an image is the wrong trade.
 */
export async function makeCover({ number, title, topic }) {
  try {
    const blob = await put(`${COVER_PREFIX}${number}-${Date.now()}.svg`, drawCover({ number, title, topic }), {
      access: 'private', contentType: 'image/svg+xml', addRandomSuffix: true,
      token: process.env.BLOB_READ_WRITE_TOKEN
    });
    return { url: coverHref(blob.pathname), kind: 'drawn', reason: null };
  } catch (err) {
    console.error('[reports] no cover at all:', err.message);
    return { url: null, kind: 'none', reason: err.message };
  }
}
