/**
 * The cover for one report, and the placeholder for an item with no picture.
 *
 * Drawn here, from the report's own number. Nothing is generated by a model
 * and nothing is fetched from an image service: the pictures in a report
 * belong to the publishers who took them, and the only image we make is this
 * one, which is a piece of our own branding rather than a depiction of
 * anything.
 *
 * It is a real design, not an error state, and that distinction carries weight
 * now. An item whose publisher offers no picture, or whose picture is a wire
 * photograph we will not point at, shows this instead - so it has to look like
 * a decision somebody made.
 *
 * Our blob store is private - it refuses `access: 'public'` outright - so the
 * stored URL is never the blob's own. It is an absolute link to
 * /api/report-cover, which streams the file to anybody who has the link. That
 * is deliberate and it is the only way round: the Monday email shows the cover,
 * and an email client fetches images with no cookies and no session.
 */
import { put } from '@vercel/blob';

/* ---------------- the drawing ---------------- */

const esc = (s) => String(s || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

/**
 * Wrap a headline to a given number of lines, on whole words.
 *
 * SVG has no text wrapping, so this measures in characters, which is close
 * enough for one typeface at one size. Truncation is the thing to avoid:
 * "Cheaper models, and when cheaper i" reads as a bug, so the last line keeps
 * an ellipsis rather than stopping mid-word.
 */
function wrap(text, perLine, maxLines) {
  /* A word longer than the line it is on cannot be wrapped, only cut. Without
     this a single long token - a model id, a URL somebody pasted into a title -
     is laid out as one line of any width and runs clean off the card, because
     SVG will happily draw text past its own viewBox. */
  const words = String(text || '').split(/\s+/).filter(Boolean)
    .flatMap((w) => {
      if (w.length <= perLine) return [w];
      const parts = [];
      for (let i = 0; i < w.length; i += perLine) parts.push(w.slice(i, i + perLine));
      return parts;
    });

  const lines = [];
  let line = '';
  for (const w of words) {
    const next = line ? `${line} ${w}` : w;
    if (next.length > perLine && line) {
      lines.push(line);
      line = w;
      if (lines.length === maxLines) break;
    } else {
      line = next;
    }
  }
  if (line && lines.length < maxLines) lines.push(line);

  const used = lines.join(' ').split(/\s+/).filter(Boolean).length;
  if (used < words.length && lines.length) {
    // Room for the ellipsis rather than one character past the edge.
    const last = lines[lines.length - 1];
    lines[lines.length - 1] = `${last.length >= perLine ? last.slice(0, perLine - 1) : last}…`;
  }
  return lines;
}

const MONTHS = ['January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December'];

/**
 * The card at the top of a report, and the one on the shelf.
 *
 * It says what the report is. An abstract field of dots was handsome and told
 * a reader nothing - in an email it arrives above the headline as a decorative
 * strip with no purpose, which is exactly how it was described.
 *
 * So it carries the words: whose report it is, the headline, and the week. No
 * report number on it, because the number is how we file these and not
 * something a reader needs; it is on the page's own meta line for anyone who
 * wants it.
 *
 * Deterministic. The same report always gets the same card, because one that
 * changes when a page is re-rendered looks like a fault. The hue is seeded
 * from the number so consecutive weeks sit apart on the shelf.
 */
export function drawCover({ number, title, topic, publishedAt }) {
  const n = Number(number) || 1;

  // Inside the brand's own band rather than around the whole wheel. Thirty
  // degrees of amber-to-orange is enough to tell two covers apart on a shelf
  // and not enough for one of them to come out lime green.
  const hue = 14 + ((n * 7) % 31);
  const a = `hsl(${hue} 95% 60%)`;
  const b = `hsl(${(hue + 14) % 360} 88% 50%)`;

  const d = publishedAt ? new Date(publishedAt) : new Date();
  const when = isNaN(d) ? '' : `${d.getDate()} ${MONTHS[d.getMonth()]} ${d.getFullYear()}`;

  // Longer headlines get smaller type rather than more lines: four lines of
  // 44pt on a 480-high card leaves no room to breathe.
  const t = String(title || 'This week in AI');
  const size = t.length > 76 ? 50 : t.length > 46 ? 58 : 66;
  const perLine = size === 50 ? 40 : size === 58 ? 34 : 29;
  const lines = wrap(t, perLine, 3);
  const lead = size + 12;
  // Bottom-anchored, so one line and three lines both sit on the same baseline.
  const firstY = 392 - (lines.length - 1) * lead;

  const dots = [];
  for (let i = 0; i < 44; i++) {
    const x = 60 + ((i * 137 + n * 29) % 1080);
    const y = 24 + ((i * 263 + n * 61) % 190);
    // The headline owns the lower half and the two brand lines own the top
    // left, so the lattice keeps out of both. A dot landing on the "I" of AI
    // FOUNDER UNIVERSITY reads as dirt on the lens.
    if (x < 640 && y > 60 && y < 150) continue;
    const r = 1.5 + ((i + n) % 4);
    dots.push(`<circle cx="${x}" cy="${y}" r="${r}" fill="${i % 6 === 0 ? a : '#ffffff'}" opacity="${i % 6 === 0 ? 0.8 : 0.09}"/>`);
  }

  return `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="480" viewBox="0 0 1200 480" role="img" aria-label="${esc(t)}">
  <defs>
    <radialGradient id="g1" cx="78%" cy="6%" r="72%">
      <stop offset="0%" stop-color="${a}" stop-opacity=".32"/><stop offset="100%" stop-color="${a}" stop-opacity="0"/>
    </radialGradient>
    <radialGradient id="g2" cx="10%" cy="98%" r="64%">
      <stop offset="0%" stop-color="${b}" stop-opacity=".18"/><stop offset="100%" stop-color="${b}" stop-opacity="0"/>
    </radialGradient>
  </defs>
  <rect width="1200" height="480" fill="#0a0a0b"/>
  <rect width="1200" height="480" fill="url(#g1)"/>
  <rect width="1200" height="480" fill="url(#g2)"/>
  ${dots.join('')}
  <text x="60" y="92" font-family="JetBrains Mono, ui-monospace, monospace" font-size="20"
        letter-spacing="5.5" fill="${a}">AI FOUNDER UNIVERSITY</text>
  <text x="60" y="126" font-family="JetBrains Mono, ui-monospace, monospace" font-size="18"
        letter-spacing="3" fill="#71717a">THE WEEKLY AI REPORT</text>
  ${lines.map((l, i) => `<text x="60" y="${firstY + i * lead}" font-family="Inter, Helvetica, Arial, sans-serif" ` +
    `font-size="${size}" font-weight="800" letter-spacing="-1.6" fill="#f4f4f5">${esc(l)}</text>`).join('\n  ')}
  ${when ? `<text x="60" y="440" font-family="JetBrains Mono, ui-monospace, monospace" font-size="19"
        fill="#a1a1aa">${esc(when)}</text>` : ''}
  <rect x="0" y="474" width="1200" height="6" fill="${a}"/>
</svg>`;
}

/* ---------------- storage ---------------- */

/* Where the cover is stored, and the one shape api/report-cover will serve.
   Anything outside this prefix is refused there, so the endpoint cannot be
   talked into streaming a lesson video or somebody's download. */
export const COVER_PREFIX = 'reports/cover-';

const site = () => (process.env.SITE_URL || 'https://aifounderuniversity.com').replace(/\/+$/, '');

/**
 * The link that goes in the database, the page and the email.
 *
 * Absolute, because the email needs it to be, and pointing at our own endpoint
 * rather than at the blob, because the blob is private and returns 403 to
 * anything without our token.
 */
export function coverHref(pathname) {
  return `${site()}/api/report-cover?key=${encodeURIComponent(pathname)}`;
}

/**
 * A cover for this report, in our own storage.
 *
 * Never throws. If it cannot be stored the report still goes out without one -
 * losing the week's report over an image is the wrong trade.
 */
export async function makeCover({ number, title, topic, publishedAt }) {
  try {
    const blob = await put(`${COVER_PREFIX}${number}-${Date.now()}.svg`, drawCover({ number, title, topic, publishedAt }), {
      access: 'private', contentType: 'image/svg+xml', addRandomSuffix: true,
      token: process.env.BLOB_READ_WRITE_TOKEN
    });
    return { url: coverHref(blob.pathname), kind: 'drawn', reason: null };
  } catch (err) {
    console.error('[reports] no cover at all:', err.message);
    return { url: null, kind: 'none', reason: err.message };
  }
}
